version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      all-gradle-updates:
        patterns:
          - "*" # This will match all gradle dependencies