name = "reai-email-worker"
main = "index.js"
compatibility_date = "2025-07-16"

[observability.logs]
enabled = true

# Uncomment below if you later need ENV vars or KV bindings.
# [vars]
# VOUCHER_API_BASE = ""
# API_TOKEN = ""
